"""Added applied_on column to DriverApplication

Revision ID: 0019f32a0774
Revises: 10d84eee8214
Create Date: 2025-07-15 13:58:48.766804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0019f32a0774'
down_revision = '10d84eee8214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applied_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_application', schema=None) as batch_op:
        batch_op.drop_column('applied_on')

    # ### end Alembic commands ###
