"""Add rejection_message to Booking

Revision ID: 10d84eee8214
Revises: a835c0228e4a
Create Date: 2025-07-14 15:02:48.507728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d84eee8214'
down_revision = 'a835c0228e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_message', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('rejection_message')

    # ### end Alembic commands ###
