"""Added added_on field to Car model

Revision ID: 955d35845ff5
Revises: 
Create Date: 2025-07-05 19:31:26.246338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955d35845ff5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_main', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('image_extra', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('added_on', sa.DateTime(), nullable=True))
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('added_on')
        batch_op.drop_column('image_extra')
        batch_op.drop_column('image_main')

    # ### end Alembic commands ###
