"""Add confirmation message to Booking

Revision ID: a835c0228e4a
Revises: a088a65a3c64
Create Date: 2025-07-12 17:44:37.256346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a835c0228e4a'
down_revision = 'a088a65a3c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmation_message', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('confirmation_message')

    # ### end Alembic commands ###
