"""Add confirmation and rejection message to driver application

Revision ID: e7992a3286df
Revises: 0019f32a0774
Create Date: 2025-07-16 16:25:22.433817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7992a3286df'
down_revision = '0019f32a0774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmation_message', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('rejection_message', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_application', schema=None) as batch_op:
        batch_op.drop_column('rejection_message')
        batch_op.drop_column('confirmation_message')

    # ### end Alembic commands ###
