"""Add unique constraint to license_number

Revision ID: e97a4e5f778b
Revises: e7992a3286df
Create Date: 2025-07-16 18:03:20.661109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e97a4e5f778b'
down_revision = 'e7992a3286df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_application', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['license_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_application', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
